### ISSUE TITLE
IP Fragmentation 

### ISSUE THREAD

**Issue by ghost** [theclam/stripe#1]
Hi, 
there is a problem when pcap file uses IP fragmentation, I guess it should first do defragmentation and then call dcap function.
I checked and noticed that after decapsulation. fragmented packets are not valid anymore. I can send you a sample pcap file. 

Thanks

**Comment by theclam** [comment]
Hi,

Yes, if the packet gets fragmented after encapsulation that would pretty much break it. I'll have to think about the best way to do this, probably either a separate utility or an intermediate file would be needed to avoid pulling the whole file into memory. It's a little bit tricky, which is why a lot of routers won't decap anything that has been fragmented in transit (it makes the process non-atomic and therefore impractical to do in hardware). Unfortunately it being so close to Christmas I won't get chance to look at this for a while... I will get around to it, though.

Thanks for the suggestions - first user and already 2 feature requests :)

Foeh

**Comment by ghost** [comment]
Hi Again, 
I developed a little C++ code in order to manage defragmentation, would it be possible to validate and integrate this code with your project?
here they are all available at  [link to my gists](https://gist.github.com/LisbethS/d0ee13e5b9d18f1101fa)
main.cpp
pcap.h 
capfunctions.h 
let me know how it goes, if they were ok let me have Commit permission  and contributing to the project.

Regards

**Comment by theclam** [comment]
Hi,

I'm sorry but I don't work in C++ and since this is a small project and I don't often have time to program / administer git I'd rather not open it up to contributions from others... Please feel free to fork the project if you would like to do so, you've brought some great ideas so far.

I do intend to add defragmentation capability but it's very tricky to be able to handle every circumstance (i.e. what if your IP payload gets fragmented, then the fully encapsulated packet gets fragmented? How should it handle missing fragments? How can you reconstruct payload fragments without invalidating the length field of the encapsulating frame?) - I have an idea for a method which should take care of fragmentation at every possible point (including multiple fragmentation) but I haven't written the code yet.

**Comment by theclam** [comment]
Hi,
I've added re-assembly support, in the few test pcap files I've used it seems to work OK. If you find any issues with it (I expect some!) then please raise another issue.
Thanks,
Foeh
