### ISSUE TITLE
Bad definition for L2TP packets - segfault

### ISSUE THREAD

**Issue by splichy** [theclam/stripe#5]
Hi, nice work, helped me a lot!

But checking L2TP only by port number isn't enough, for example DNS packet from port 53 to port 1701.

It's in stripe.c line 255. 

Frame causing segfault attached.
[stripe-segfault.pcap.zip](https://github.com/theclam/stripe/files/86700/stripe-segfault.pcap.zip)

Regards

**Comment by theclam** [comment]
Hi,

Thanks for the feedback and especially for providing the pcap!

It doesn't just check port numbers, it inspects values in the payload to see whether expected values are there as well so in theory it should be unlikely to match anything else. There's not much more that can be done in that respect (unless you have a suggestion?).

I think I can see what is wrong, though. The code is based on "dechap" which I wrote to pull CHAP authentications out of (amongst other things) L2TP datagrams. The fail-safe mechanism that used was to just discard anything that initially looked like L2TP but then turned out not to be by returning a null pointer. In stripe it should return the frame rather than a null.

I will attempt a fix when I get a few minutes, unfortunately that might be a while! I've often thought the L2TP section could do with a cleanup (there is still an AVP decoding section in there which serves no purpose) so this is overdue.

Thanks,

Foeh

**Comment by theclam** [comment]
OK, that was interesting. Apparently I never got L2TP decapsulation anywhere near working!  In fact there were a few sanity checks under various protocols which, if they failed, would have caused similar SEGFAULTs.

I've made it work for basic L2TPv2 data frames as generated by Cisco IOS LAC / LNS and, more importantly, made it behave gracefully if it finds anything it can't decapsulate.

I've updated the source and the Mac binary but I still need to upload a new Windows binary. Can you please re-test and let me know if you find any further issues with it?

Thanks,

Foeh

**Comment by theclam** [comment]
Hi,

I'm pretty sure this is fixed now, I'll leave it another few days for a response but if not then I'll close the issue down.

Thanks for the helpful feedback!

Foeh

**Comment by theclam** [comment]
Well that was more than a few days but no response so I'll guess it works fine now. Thanks for the feedback!
